# Generated by Django 3.1.5 on 2021-01-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.PositiveIntegerField()),
                ('strength', models.IntegerField()),
                ('description', models.TextField()),
                ('alive', models.BooleanField()),
            ],
        ),
    ]
