# Generated by Django 3.2.11 on 2022-01-20 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resistanceapp', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resistanceapp.category'),
            preserve_default=False,
        ),
    ]
