# Generated by Django 3.2.11 on 2022-01-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resistanceapp', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
