# Generated by Django 2.0.1 on 2018-01-19 19:33

from django.db import migrations

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Category = apps.get_model("resistanceapp", "Category")
    db_alias = schema_editor.connection.alias
    Category.objects.using(db_alias).bulk_create([
        Category(name="Normal", description="Just normals"),
        Category(name="Jedi", description="Cool jedis"),
        Category(name="Administrators", description="heh"),
    ])

def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    Category = apps.get_model("resistanceapp", "Category")
    db_alias = schema_editor.connection.alias
    Category(name="Normal", description="Just normals").delete()
    Category(name="Jedi", description="Cool jedis").delete()
    Category(name="Administrators", description="heh").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('resistanceapp', '0002_category'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
