# Generated by Django 2.0.1 on 2018-01-19 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resistanceapp', '0003_auto_20180119_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resistanceapp.Category'),
            preserve_default=False,
        ),
    ]
