# Generated by Django 3.2.11 on 2022-01-10 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resistanceapp', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resistanceapp.category'),
        ),
    ]
