# Generated by Django 2.0.1 on 2018-01-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resistanceapp', '0004_soldier_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
